/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cn.wuchuheng.tmp;

/**
 * Library {
 */
public class Library {
    Library(){}
    /**
     *  Print message.
     */
    public void printMessage() {
        System.out.print("Are you ok?");
    }

    /**
     * someLibraryMethod
     *
     * @return boolean
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
